name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    permissions:
      contents: write  # needed to create the release and upload assets
      id-token: write  # enable GitHub OIDC token issuance for this job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Build
        run: dotnet build ./src/RekhtaDownloader/RekhtaDownloader.csproj --configuration Release -p:Version=1.1.${{ github.run_number }}

      - name: Publish win-x64 App
        run: dotnet publish ./src/RekhtaDownloader.Console/RekhtaDownloader.Console.csproj -r win-x64 -c Release --self-contained

      - name: Zip  win-x64 artifacts
        working-directory: ./src/RekhtaDownloader.Console/bin/Release/net10.0/win-x64/publish
        run: zip -qq -r release-win-x64-1.1.${{ github.run_number }}.zip .

      - name: Publish win-x86 App
        run: dotnet publish ./src/RekhtaDownloader.Console/RekhtaDownloader.Console.csproj -r win-x86 -c Release --self-contained

      - name: Zip  win-x86 artifacts
        working-directory: ./src/RekhtaDownloader.Console/bin/Release/net10.0/win-x86/publish
        run: zip -qq -r release-win-x86-1.1.${{ github.run_number }}.zip .

      - name: Create Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          name: 1.1.${{ github.run_number }}
          tag_name: 1.1.${{ github.run_number }}
          files: |
            ./src/RekhtaDownloader.Console/bin/Release/net10.0/win-x64/publish/release-win-x64-1.1.${{ github.run_number }}.zip
            ./src/RekhtaDownloader.Console/bin/Release/net10.0/win-x86/publish/release-win-x86-1.1.${{ github.run_number }}.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}

       # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user:  ${{ secrets.NUGET_USER }} # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address

      # Push the package
      - name: NuGet push
        run: dotnet nuget push src/RekhtaDownloader/bin/Release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
